<h2>Üdvözöljük!</h2>
<p>Az oldal sugárhajtású harci repülőgépeket mutat be röviden. Elsősorban az alábbi videókban látható gépekről lesz szó.</p>
<h3>Hangolódjunk:</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/RYE5ENctJLE?si=vJP83MpmdD9My_d0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
<video width="560" height="315" controls>
    <source src="./images/video.mp4" type="video/mp4">
</video><h3>F-14 Tomcat</h3>
<img src="./images/f14.jpg" alt="miért nem jó">
<p>Az F-14-es eredetileg a flotta légvédelmét szolgálta légifölény-vadászgépként. Az F-4-eseket váltotta fel. 1970-ben repült először, hadrendbe 1973-ban állították a haditengerészetnél. Irán is vásárolt belőle 79 darabot, még az 1979-es forradalom előtt. Ezekhez az USA nem szállít alkatrészt, ezért már nem repülnek (habár 1989-ben láttak néhányat repülni). Az erősebb hajtóművel szerelt B-változat 1987-ben lépett szolgálatba. További radar-, elektronikus és rakétarendszer-fejlesztés eredménye lett a D változat (Super Tomcat). Az A/A+ változatok egy részét 1989-től kezdve továbbfejlesztették D-változattá, illetve új gépek is készültek. Ezek már képesek földi célok elleni precíziós fegyverek hordozására, Afganisztánban 2002-ben be is vetették őket. Nagy, gyors, nehéz vadászgép, nagy fegyverterheléssel. Kétüléses, két hajtóműves harcigép. Sárkányszerkezetét eredetileg 6000 levegőben töltött órára tervezték, ezt később kitolták 7200 órára. Jellegzetessége a változtatható szárnyállás, mint az F-111-esnek, a MiG-23/27-esnek, a Tornadónak, vagy éppen a B-1-esnek. Ez számítógép-vezérelt, de kézi vezérlésre is kapcsolható. Fel- és leszálláshoz 20°-ra, nagysebességű repüléshez 68°-ra állítja az automatika, de a hajófedélzeten tároláshoz 75 fokig hátratolható. A szárnymozgás sebessége 7,5 fok/mp. A pilóták kettős 0-katapultülésben ülnek.</p>
<h3>Su-57</h3>
<img src="./images/su-57.jpg" alt="miért nem jó">
<p>A Szu-57 (vagy PAK–FA, az orosz Перспективный авиационный комплекс фронтовой авиации, azaz a Front Légierő Perspektivikus Repülő-komplexuma, a tervezőirodában használt saját elnevezése T–50) szuperszonikus, ötödik generációs vadászbombázó repülőgép, melyet a Szuhoj-tervezőiroda fejlesztett, a jelenlegi MiG–29 és Szu–27 repülőgépek leváltására, a MiG 1.44 és a Szuhoj Szu–47 Berkut kísérleti repülőgépekkel szerzett tapasztalatok alapján, az F–22 Raptor és az F–35 Lightning II amerikai repülőgépek ellensúlyozására. A repülőgép fejlesztésében India is részt vett, itt a program neve FGFA (Fifth Generation Fighter Aircraft, angolul Ötödik Generációs Vadászrepülőgép). A gép rendszeresítését eredetileg 2015-től tervezte az Orosz Légierő,[4] de a hajtóművek áttervezése miatt csak 2021 elejére állhatott szolgálatba a típus.[5]A sorozatgyártás megkezdődött, és már tervezik a 2.0 verziót is.</p>
<h3>Az oldal címe:</h3>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2726.3375296155727!2d19.66695091525771!3d46.89607994478184!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4743da7a6c479e1d%3A0xc8292b3f6dc69e7f!2sPallasz+Ath%C3%A9n%C3%A9+Egyetem+GAMF+Kar!5e0!3m2!1shu!2shu!4v1475753185783" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>